name: adv-datamining
channels:
  - conda-forge
dependencies:
  - jupyter=Hoofdstuk1.0
  - matplotlib=3.8
  - notebook=7.Hoofdstuk1
  - pandas=2.2
  - pip=24.0
  - python=3.11
  - scikit-learn=Hoofdstuk1.4
  - tensorflow=2.15
